"""Create tweets table

Revision ID: 52dfdfdfac8e
Revises: f5297e08dfc9
Create Date: 2025-06-16 08:51:09.935853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52dfdfdfac8e'
down_revision = 'f5297e08dfc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('place', sa.String(length=255), nullable=True),
    sa.Column('tweet', sa.Text(), nullable=True),
    sa.Column('mentions', sa.String(length=255), nullable=True),
    sa.Column('urls', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('replies_count', sa.Integer(), nullable=True),
    sa.Column('retweets_count', sa.Integer(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('hashtags', sa.String(length=255), nullable=True),
    sa.Column('cashtags', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('retweet', sa.Boolean(), nullable=True),
    sa.Column('quote_url', sa.String(length=255), nullable=True),
    sa.Column('video', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('translate', sa.Text(), nullable=True),
    sa.Column('trans_src', sa.String(length=50), nullable=True),
    sa.Column('trans_dest', sa.String(length=50), nullable=True),
    sa.Column('keyword_used', sa.String(length=255), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    # ### end Alembic commands ###
