"""Update Tweet model with new columns and types

Revision ID: 726005ab5754
Revises: 52dfdfdfac8e
Create Date: 2025-06-21 09:18:20.722244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '726005ab5754'
down_revision = '52dfdfdfac8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_count', sa.Integer(), nullable=True))
        batch_op.alter_column('video',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('video',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
        batch_op.drop_column('quote_count')

    # ### end Alembic commands ###
